Account/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Account'
urlpatterns = [
    path('user_login', auth_views.LoginView.as_view(template_name='Account/login.html'), name='login' ),
    path('user_logout', auth_views.LogoutView.as_view(template_name='Account/logout.html'), name='logout' ),
    path('new_user_register/',views.Registerview.as_view(),name='user_register'),
]

Ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    # path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('Account.urls',namespace='account')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('shop.urls')),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name= 'shop'

urlpatterns = [
    path('',views.Product_List.as_view(),name='product_list'),
    path('addtocart/<slug:slug>/',views.addtocart,name='addtocart'),
    path('cartlist',views.cartlist.as_view(),name='cartlist'),
    path('remove_from_cart/<slug:slug>/',views.remove_product_from_cart,name='remove_from_cart'),
    path('create_product/<slug:slug>/',views.CreateProduct,name='create_product'),
    path('order_list/',views.OrderList.as_view(),name='order_list'),
    path('cancel_order/<slug:slug>/<int:pk>',views.CancelOrder,name='cancelorder'),
    path('searchquery/',views.searchquery,name='searchquery'),
    path('final_order/<slug:slug>/<int:pk>',views.final_order,name='final_order'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/shop/css/footer.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/shop/css/base.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Document</title>
</head>
<style>
  body{
    background: rgb(2, 184, 230);;
    font-size: 2rem !important;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
     }
    *{
        font-size: 20px;
    }

</style>
<body>
    <header class="header">
        {% if user.is_authenticated %}
        <nav  class="navbar navbar-expand-lg navbar-dark bg-dark ">
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span style="background-color: black;" class="navbar-toggler-icon"></span>
              
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{%url 'shop:product_list' %}"><span class="fa fa-home"></span> Home <span class="sr-only">(current)</span></a>
                </li>
               
                <li class="nav-item  ">
                  <a  class="nav-link" href="{% url 'shop:cartlist'  %}">My Cart List  <span style="margin: 2px;" class="badge bg-secondary">{{user.cart.count}}</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:order_list'  %}">My Order List<span style="margin: 2px;" class="badge bg-danger">{{user.orders.count}}</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Category
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Jeans</a>
                    <a class="dropdown-item" href="#">Tops</a>
                    <!-- <div class="dropdown-divider"></div> -->
                    <a class="dropdown-item" href="#">Shirt and T-Shirts</a>
                  </div>
                </li>
                
              </ul>
              <form action="{%url 'shop:searchquery'%}" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='product'>
                <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
              </form>
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'Account:logout'  %}">Logout</a>
                </li>
                <li class="nav-item">
                  <a class="navbar-brand">@Hello,{{user.get_full_name}}</a>
                </li>
              </ul>
            </div>
          </nav>
        
        {%else%}
        <nav class="navbar navbar-expand-lg navbar-inverse bg-light">
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:product_list' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Account:login' %}">Login</a>
                </li>
                <li class="nav-items">
                    <a class="nav-link" href="{%url 'Account:user_register'%}"> Register here</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Category
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li>
                
              </ul>
              <form action="{%url 'shop:searchquery'%}" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='product'>
                <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>
       
        {%endif%}
    </header>

    <div >
      {% block content %}
      {% endblock %}
      </div>


    
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init(
     {
  
     offset: 200, // offset (in px) from the original trigger point
     delay: 0, // values from 0 to 3000, with step 50ms
     duration: 100,
  
     }
  
        );
    </script>
  

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<div class="footer">
    <div class="inner-footer">
  
  <!--  for company name and description -->
      <div class="footer-items">
        <h1>Company Name</h1>
        <p>Description of any product or motto of the company.</p>
      </div>
  
  <!--  for quick links  -->
      <div class="footer-items">
        <h3>Quick Links</h3>
        <div class="border1"></div> <!--for the underline -->
          <ul>
            <a href="#"><li>Home</li></a>
            <a href="#"><li>Search</li></a>
            <a href="#"><li>Contact</li></a>
            <a href="#"><li>About</li></a>
          </ul>
      </div>
  
  <!--  for some other links -->
      <div class="footer-items">
        <h3>Recipes</h3>
        <div class="border1"></div>  <!--for the underline -->
          <ul>
            <a href="#"><li>Indian</li></a>
            <a href="#"><li>Chinese</li></a>
            <a href="#"><li>Mexican</li></a>
            <a href="#"><li>Italian</li></a>
          </ul>
      </div>
  
  <!--  for contact us info -->
      <div class="footer-items">
        <h3>Contact us</h3>
        <div class="border1"></div>
          <ul>
            <li><i class="fa fa-map-marker" aria-hidden="true"></i>XYZ, abc</li>
            <li><i class="fa fa-phone" aria-hidden="true"></i>123456789</li>
            <li><i class="fa fa-envelope" aria-hidden="true"></i>xyz@gmail.com</li>
          </ul> 
        
  <!--   for social links -->
          <div class="social-media">
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-google-plus-square"></i></a>
          </div> 
      </div>
    </div>
    
  <!--   Footer Bottom start  -->
    <div class="footer-bottom">
      Copyright &copy; Food and Burps 2020.
    </div>
  </div>