Ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    # path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('Account.urls',namespace='account')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('shop.urls')),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name= 'shop'

urlpatterns = [
    path('',views.Product_List.as_view(),name='product_list'),
    path('addtocart/<slug:slug>/',views.addtocart,name='addtocart'),
    path('cartlist',views.cartlist.as_view(),name='cartlist'),
    path('remove_from_cart/<slug:slug>/',views.remove_product_from_cart,name='remove_from_cart'),
    path('create_product/<slug:slug>/',views.CreateProduct,name='create_product'),
    path('order_list/',views.OrderList.as_view(),name='order_list'),
    path('cancel_order/<slug:slug>/<int:pk>',views.CancelOrder,name='cancelorder'),
    path('searchquery/',views.searchquery,name='searchquery'),
    path('final_order/<slug:slug>/<int:pk>',views.final_order,name='final_order'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import fields
from django.urls import reverse
from django.utils.text import slugify
from datetime import datetime
# Create your models here.

# Address
# 2.Product
# 3.Order
# 4.AddToCart
# 5.ProductOrder
# 6.WishList

class Address(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='address')
    mobile_no=models.CharField(max_length=12)
    Flat_No=models.CharField(max_length=10)
    Area_Colony=models.CharField(max_length=100)
    Landmark=models.TextField()
    Town_City=models.CharField(max_length=20)
    State=models.CharField(max_length=20)
    Pincode=models.CharField(max_length=6)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering=['Pincode','user']
    
    # def get_absolute_url(self):

    #     return reverse('shop:Address_list')
class Product(models.Model):
        product_name=models.CharField(max_length= 100)
        slug=models.SlugField(unique=True)
        product_discription=models.TextField()
        product_price=models.IntegerField()
        product_picture=models.ImageField(upload_to='images',blank = True,null = True)
        product_launch_date=models.DateTimeField(default=datetime.now())
        product_manufacturer=models.TextField()
        product_rating=models.IntegerField()


        def __str__(self):
            return self.product_name


        def save(self,*args,**kwargs):
            self.slug=slugify(self.product_name)
            super().save(*args,**kwargs)


	# def get_absolute_url(self):
	# 	return reverse('product:single',kwargs={'slug':self.slug},)


        class Meta():
            ordering=['product_name']
        
class Order(models.Model):
        
        user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='orders')
        order_date=models.DateTimeField(default=datetime.now())
        product=models.ManyToManyField(Product,related_name='orders',through='ProductOrder')

        def __str__(self):
            return self.user.username


	# def get_absolute_url(self):   
	# 	return reverse('app:myorder')


        class Meta():
            ordering=['order_date']





class ProductOrder(models.Model):
	order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='products')
	product=models.ForeignKey(Product,on_delete=models.CASCADE)


	def __str__(self):
		return str(self.order.user.username)



class AddCart(models.Model):
	product=models.ForeignKey(Product,related_name='cart',on_delete=models.CASCADE)
	user=models.ForeignKey(User,related_name='cart',on_delete=models.CASCADE)

	def __str__(self):
		return str(self.product)



	# def get_absolute_url(self):
	# 	return reverse('order:succe',kwargs={'pk':self.pk})


	class Meta():
		ordering=['user']


# class WishList(models.Model):
#     product=models.ForeignKey(Product,related_name='cart',on_delete=models.CASCADE)
#     user=models.ForeignKey(User,related_name='cart',on_delete=models.CASCADE)
    

shop/views.py
from django.contrib.auth import login
from django.db import models
from django.urls import reverse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import *
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from . import Checksum
# Create your views here.
MERCHANT_KEY="P1ZLXK_oh0S_C1zu"
from .models import *
class Product_List(ListView):
    model=Product
    template_name='shop/product_list.html'
    context_object_name='list_item'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['jeans']=Product.objects.filter(product_name__icontains='jeans')
        context['shirt']=Product.objects.filter(product_name__icontains='shirt')[:3]
        context['top']=Product.objects.filter(product_name__icontains='top')[:3]
        
        return context

def addtocart(request,slug):
        if(not(request.user.is_authenticated)):
            return redirect("account:login")
        else:
            product=get_object_or_404(Product,slug=slug)
            
            
            addcart=AddCart.objects.filter(user=request.user,product=product)
            if addcart:
                return redirect('shop:cartlist')
            else:
        
                AddCart.objects.create(user=request.user,product=product)
        
            return redirect('shop:cartlist')

class cartlist(ListView):
    model=AddCart
    template_name='shop/add_to_cart.html'


# def AddToCart(request,pk):

# 	product=get_object_or_404(Product,pk=pk)
# 	print(product)
# 	try:
# 		AddCart.objects.create(user=request.user,product=product)

# 	except:
# 		messages.warning(request,'Please Login')
# 		redirect('account:login')

# 	else:
# 		messages.success(request,'your paroduct is saved in cart')

# 	return redirect('app:cartlist')
@login_required
def remove_product_from_cart(request,slug):
    product=get_object_or_404(Product,slug=slug)
    addcart=get_object_or_404(AddCart,user=request.user,product=product)
    addcart.delete()
    return redirect('shop:cartlist')

def CreateProduct(request,slug):
    if(not(request.user.is_authenticated)):
            return redirect("account:login")
    else:
        order=Order(user=request.user,order_date=datetime.now())
        order.save()
        product=get_object_or_404(Product,slug=slug)
        param_dict={
        
        "MID": "bENzWU52249925662751",
        "ORDER_ID": str(order.pk),
        "CUST_ID": "tanisha.modi.23@gmail.com",
        "TXN_AMOUNT": str(product.product_price),
        "CHANNEL_ID": "WEB",
        "INDUSTRY_TYPE_ID": "Retail",
        "WEBSITE": "WEBSTAGING",
        'CALLBACK_URL':f"http://127.0.0.1:8000/final_order/{slug}/{order.pk}"
        }
        param_dict['CHECKSUMHASH']=Checksum.generate_checksum(param_dict,MERCHANT_KEY)
        return render(request,'shop/paytm.html',{'param_dict':param_dict})
        # product=get_object_or_404(Product,slug=slug)
        # return render(request,'shop/order.html',{'product':product})
       

class OrderList(TemplateView):
    template_name='shop/order_list.html'
@login_required
def CancelOrder(request,slug,pk):
    product=get_object_or_404(Product,slug=slug)
    order=get_object_or_404(Order,pk=pk)
    order_product=ProductOrder.objects.filter(order=order,product=product)
    if order_product:
        order_product.delete()
        order.delete()
        return redirect("shop:order_list")
    else:
        return redirect("shop:order_list")
def searchquery(request):
    if request.method=='GET':
        query=request.GET['product']
        product_list=Product.objects.filter(product_name__icontains=query)
        return render(request,'shop/product_list.html',{'list':product_list})

@csrf_exempt
def final_order(request,slug,pk):
        form=request.POST
        response_dict={}
        for i in form.keys():
            response_dict[i]=form[i]
            if i=='CHECKSUMHASH':
                checksum=form[i]
        verify=Checksum.verify_checksum(response_dict,MERCHANT_KEY,checksum)
        if verify:
            if response_dict['RESPCODE'] =='01':
                print("order success full")
                product=get_object_or_404(Product,slug=slug)
               
                order=get_object_or_404(Order,pk=pk)
                ProductOrder.objects.create(product=product,order=order)
                
            else:
                print("not successful" + response_dict['RESPMSG'])
        product_list=Product.objects.all()
        return redirect('shop:order_list')
    # product=get_object_or_404(Product,slug=slug)
    # order=get_object_or_404(Order,pk=pk)
    # try:
    #     ProductOrder.objects.create(order=order,product=product)
       
    # except Exception as e:
    #     print("sorry we are not creating any object")
    # return redirect('shop:order_list')

shop/templates/shop/add_to_cart.html
{% extends "base.html" %}
{% block content %}
  <div class="container ctr">
  {% if user.cart.all %}
  {% for p in user.cart.all %}
  <div class="card crd">
      <img class="img-top"  src="{{p.product.product_picture.url}}" alt="">

      <div class="card-body body">
          <h5 class="card-title title">{{p.product.product_name}}</h5>
         
          <div class="card-footer footer">
              
              <h3><span>Rs.{{p.product.product_price}}</span></h3>
              <a class="btn btn-fluid btn-warning" href="{% url 'shop:create_product'  slug=p.product.slug %}">Buy Now</a>
              <a class="btn btn-fluid btn-info" href="{% url 'shop:remove_from_cart' slug=p.product.slug %}">Remove</a>

          </div>
      </div>
  </div>
{% endfor %}

  

      {% else %}
      <h2>Soory There is product in your cartlist</h2>
  {% endif %}
  </div>      
{% endblock content %}

shop/templates/shop/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Order Successfull</h1>
      {% for key,value in response.items  %}
        <ul>
            <li>{{key}}</li>
            <li>{{value}}</li>
        </ul>
        {%endfor%}
</body>
</html>
  
      
        
   
     

shop/templates/shop/order_list.html
{% extends "base.html" %}
{% block content %}
  <h1>{{response}}</h1>
  <div class="container ctr">
  {% if user.orders.all %}     
  {% for order in user.orders.all %}
  {%for p in order.product.all %}

  <div class="card crd">
      <img class="img-top"  src="{{p.product_picture.url}}" alt="">

      <div class="card-body body">
          <h5 class="card-title title">{{p.product_name}}</h5>
         
          <div class="card-footer footer">
              
              <h3><span>Rs.{{p.product_price}}</span></h3>
             
              <a class="btn btn-fluid btn-danger" href="{%url 'shop:cancelorder' slug=p.slug pk=order.pk %}">Cancel</a>

          </div>
      </div>
  </div>
  {%endfor%}
{% endfor %}
</div>
      {% else %}
      <h2>Sorry There is product in your Order List</h2>
  {% endif %}
      
{% endblock content %}

shop/templates/shop/paytm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Merchant Check Out Page</h1></br>
    <table align='center'>
        <tr>
            <td><STRONG>Transaction is being processed,</STRONG></td>
        </tr>
        <tr>
            <td><font color='blue'>Please wait ...</font></td>
        </tr>
        <tr>
            <td>(Please do not press 'Refresh' or 'Back' button</td>
        </tr>
    </table> 
    <form NAME='TESTFORM' method="post" action="https://securegw-stage.paytm.in/theia/processTransaction" >
        {% for key,value in param_dict.items  %}
          <input type="hidden" name="{{key}}" value="{{value}}">
        {% endfor %}
           
    </form>
    <script>
         document.forms[0].submit();
    </script>
</body>
</html>

shop/templates/shop/product_list.html
{% extends "base.html" %}
{% block content %}
<style>
    .footerr{
        display: none;
        height: 40px !important;
        padding: 5px;
    }
 
   .crd:hover .footerr{
    display: flex;
   }

   .ctr
{
display: flex; 
flex-wrap: wrap;
justify-content: space-between;
align-items: center;


}
   
</style>
<div style="display: flex;justify-content: space-around; height: 30vh;">
<div data-aos="fade-right">
    <h1 class="text-center;">Filters</h1>
    <form action="{%url 'shop:searchquery'%}" method="get">
        <label for="jeans">Filter By jeans</label>
        <input type="radio" name="product" id="jeans" value="jeans">
        <div></div>
        <label for="top">Filter By Top</label>
        <input type="radio" name="product" id="top" value="top">
        <div></div>
        <label for="shirt">Filter By shirt</label>
        <input type="radio" name="product" id="shirt" value="shirt">
        <div></div>
       <input type="submit" class="btn btn-primary btn-lg btn-fluid" value="Filter">
    </form>
</div>
<div style="height:100vh">
<div  class="container ctr">
      
    {% if list %}
        {% for product in list %}
          <div data-aos="fade-up-right" class="card crd">
              <img class="img-top"  src="{{product.product_picture.url}}" alt="">
      
              <div class="card-body body">
                  <h5 class="card-title title">{{product.product_name}}</h5>
                 
                  <div class="card-footer footerr">
                      <a class="btn btn-fluid btn-warning" href="{%url 'shop:addtocart' slug=product.slug%}">Add to Cart</a>
                      <a class="btn btn-fluid btn-success" href="{% url 'shop:create_product' slug=product.slug %}">Buy Now</a>
                      <h3><span>Rs.{{product.product_price}}</span></h3>
                  </div>
              </div>
          </div>
        {% endfor %}
   
</div>
{%else%}
<div style="width: 100%;" class="div-head">
    <h1 class="text-center">Top</h1>
</div>

  <div  class="container ctr">
      
      {% if top %}
          {% for product in top %}
            <div data-aos="flip-right" class="card crd">
                <img class="img-top"  src="{{product.product_picture.url}}" alt="">
        
                <div class="card-body body">
                    <h5 class="card-title title">{{product.product_name}}</h5>
                   
                    <div class="card-footer footerr">
                        <a class="btn btn-fluid btn-warning" href="{%url 'shop:addtocart' slug=product.slug%}">Add to Cart</a>
                        <a class="btn btn-fluid btn-success" href="{% url 'shop:create_product' slug=product.slug %}">Buy Now</a>
                        <h3><span>Rs.{{product.product_price}}</span></h3>
                    </div>
                </div>
            </div>
          {% endfor %}
      {% endif %}
  </div>
  <div style="width: 100%;" class="div-head">
  <h1 class="text-center">T-Shirts and Shirts</h1></div>
  <div  class="container ctr">
      
      {% if shirt %}
          {% for product in shirt %}
            <div data-aos="flip-right" class="card crd">
                <img class="img-top"  src="{{product.product_picture.url}}" alt="">
        
                <div class="card-body body">
                    <h5 class="card-title title">{{product.product_name}}</h5>
                   
                    <div class="card-footer footerr">
                        <a class="btn btn-fluid btn-warning" href="{%url 'shop:addtocart' slug=product.slug%}">Add to Cart</a>
                        <a class="btn btn-fluid btn-success" href="{% url 'shop:create_product' slug=product.slug %}">Buy Now</a>
                        <h3><span>Rs.{{product.product_price}}</span></h3>
                    </div>
                </div>
            </div>
          {% endfor %}
      {% endif %}
      </div>
      <div style="width: 100%;" class="div-head">
      <h1 class="text-center">Jeans</h1></div>
      <div style="margin-bottom: 50px;" class="container ctr">
     
      {% if jeans %}
          {% for product in jeans %}
            <div  data-aos="flip-left" class="card crd">
                <img class="img-top"  src="{{product.product_picture.url}}" alt="">
        
                <div class="card-body body">
                    <h5 class="card-title title">{{product.product_name}}</h5>
                   
                    <div class="card-footer footerr">
                        <a class="btn btn-fluid btn-warning" href="{%url 'shop:addtocart' slug=product.slug%}">Add to Cart</a>
                        <a class="btn btn-fluid btn-success" href="{% url 'shop:create_product' slug=product.slug %}">Buy Now</a>
                        <h3><span>Rs.{{product.product_price}}</span></h3>
                    </div>
                </div>
            </div>
          {% endfor %}
      {% endif %}
    
          
  </div>
  </div>
</div>
  {%endif%}
  {% endblock content %}
  